- hosts: 'osquery_windows'
  tasks:
    # Request variables for playbook
    - import_tasks: 'roles/osquery/init.yml'
      delegate_to: localhost
      run_once: True

    # Install/Setup Osquery on linux
    - import_tasks: 'roles/osquery/windows/setup_osquery.yml'
