version: '2.2'
services:
  zeek-manager:
    container_name: zeek-manager
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-zeek-cluster-manager
      args:
        zeek_interface: 'ens18'
    volumes:
      - zeek-manager-logs:/opt/bro/logs
      - zeek-manager-configs:/opt/bro/etc
    network_mode: bridge
    extra_hosts:
      - "zeek-worker:1.1.1.1"
    # networks:
    #   - zeek-net
    depends_on:
      - zeek-proxy
      - zeek-worker
  zeek-proxy:
    container_name: zeek-proxy
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-zeek-cluster-proxy
    volumes:
      - zeek-proxy-configs:/opt/bro/etc
    network_mode: bridge
    # networks:
    #   - zeek-net
  zeek-worker:
    container_name: zeek-worker
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-zeek-cluster-worker
    network_mode: host
    ports:
      - '5000:22'
    volumes:
      - zeek-worker-configs:/opt/bro/etc
    cap_add:
      - NET_ADMIN

volumes:
  zeek-manager-logs:
  zeek-manager-configs:
  zeek-proxy-configs:
  zeek-worker-configs:

networks:
  zeek-net:
