FROM ubuntu:18.04 as zeek-proxy

# Install things
RUN apt-get update -y && apt-get install net-tools

# Copy Zeek from build
COPY --from=zeek-build /opt/bro /opt/bro

#### Setup SSH ####
# Install openssh
RUN apt-get update -y && apt-get install openssh-server -y

# Create directory
RUN mkdir /root/.ssh && chmod 700 /root/.ssh

# Copy SSH keys
COPY .ssh/id_rsa.pub /tmp/id_rsa.pub

# Add key
RUN cat /tmp/id_rsa.pub > /root/.ssh/authorized_keys

## Copy Zeek config
COPY node-none.cfg /opt/bro/etc/node.cfg

## Supervisor
RUN apt-get install python3 supervisor -y
COPY supervisor-slave.conf /etc/supervisor/conf.d/supervisord.conf

# Entrypoint
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]
