FROM ubuntu:18.04 as zeek-manager

# Copy Zeek from build
COPY --from=zeek-build /opt/bro /opt/bro

## Copy Zeek config
COPY node-cluster.cfg /opt/bro/etc/node.cfg

## Copy SSH keys
COPY .ssh/id_rsa /root/.ssh/id_rsa
COPY .ssh/id_rsa.pub /root/.ssh/id_rsa.pub

## Supervisor
RUN apt-get update -y && apt-get install python3 supervisor
COPY supervisor.conf /etc/supervisor/conf.d/supervisord.conf

# Entrypoint
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]