############################################## Suricata ##############################################
suricata_dir: '/tmp/suricata'
suricata_version: '5.0.3'
suricata_tar_url: 'https://www.openinfosecfoundation.org/download/suricata-{{ suricata_version }}.tar.gz'

suricata_username: 'suricata'

suricata_configure_prefix: '/usr'
suricata_configure_sysconfdir: '/etc'
suricata_configure_localstatedir: '/var'
suricata_configure_libpfring_includes: '/usr/local/include'
suricata_configure_libpfring_libraries: '/usr/local/lib'
suricata_configure: >
  LIBS="-lrt" ./configure
  --prefix={{ suricata_configure_prefix }}
  --sysconfdir={{ suricata_configure_sysconfdir }}
  --localstatedir={{ suricata_configure_localstatedir }}
  --enable-pfring
  --with-libpfring-includes={{ suricata_configure_libpfring_includes }}
  --with-libpfring-libraries={{ suricata_configure_libpfring_libraries }}

suricata_rules_dir: '/etc/suricata/rules'

############################################## PF_RING ##############################################
pfring_dir: '/opt/pf_ring'
pfring_version: '7.6.0'
pfring_tar_url: 'https://github.com/ntop/PF_RING/archive/{{ pfring_version }}.tar.gz'
