- hosts: 'rsyslog-agents'
  become: true
  become_user: root
  tasks:
    - include_vars: 'group_vars/graylog.yml'
    - include_vars: 'group_vars/logging.yml'
    - import_tasks: 'roles/rsyslog/setup_rsyslog.yml'
