version: "3"
services:
  resp:
    restart: always
    build: .
    ports:
      - "137:137"
      - "138:138"
      - "139:139"
      - "389:389"
      - "445:445"
    volumes:
      - /srv/responder/logs:/Responder/logs
