version: "3.9"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.1
    networks:
      - logging-backend
    ports:
      - 5044:5044
    configs:
      #- source: logstash-config
      #  target:
      - source: logstash-beats-input
        target: /usr/share/logstash/pipeline/logstash.conf
      - source: logstash-file-output
        target: /usr/share/logstash/pipeline/30-output-file.conf
    secrets:
      - logstash-tls-key
      - logstash-tls-crt
      - logstash-tls-server-ca
      - filebeat-tls-client-ca

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.11.1
    networks:
      - logging-backend
    configs:
      - source: filebeat-config
        target: /usr/share/filebeat/filebeat.yml
      #- source: filebeat-file-input
      #  target:
    secrets:
      - filebeat-tls-key
      - filebeat-tls-crt
      - filebeat-tls-client-ca
    #extra_hosts:
    #  - "logstash01.servers.logging.hackinglab.local:logstash"
    depends_on:
      - logstash

networks:
  logging-backend:

secrets:
  #### Filebeat ####
  filebeat-tls-key:
    file: ./conf/tls/filebeat01_clients_logging_hackinglab.local.key
  filebeat-tls-crt:
    file: ./conf/tls/filebeat01_clients_logging_hackinglab.local.crt
  filebeat-tls-client-ca:
    file: ./conf/tls/server_logging_int/server_logging_int.crt
  #### Logstash ####
  logstash-tls-key:
    file: ./conf/tls/logstash01_servers_logging_hackinglab.local.key
  logstash-tls-crt:
    file: ./conf/tls/logstash01_servers_logging_hackinglab.local.crt
  logstash-tls-server-ca:
    file: ./conf/tls/client_logging_int/clients_logging_int.crt


configs:
  filebeat-config:
    file: ./conf/filebeat/filebeat-docker.yml
  #filebeat-file-input:
  #  file: ./conf/filebeat/filebeat-docker.yml
  #logstash-config:
  #  file: ./
  logstash-beats-input:
    file: ./conf/logstash/02-input-beats-docker.conf
  logstash-file-output:
    file: ./conf/logstash/30-output-file.conf
