version: '2.2'
services:
  zeek:
    build: .
    container_name: zeek-standalone
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - zeek-logs:/opt/bro/logs
      - zeek-configs:/opt/bro/etc

volumes:
  zeek-logs:
  zeek-configs:
