################################## General ##################################

################################## Tools ##################################
#### Osquery ####
osquery_version: '3.3.2'
polylogyx_osq_ext_bin_url: 'https://raw.githubusercontent.com/polylogyx/osq-ext-bin/master/plgx_win_extension.ext.exe'

#### Filebeat ####
filebeat_version: '7.5.0'

#### Logstash ####
logstash_ip_addr: '10.150.100.210'
logstash_port: 5044

################################## Slack ##################################
slack_channel:
slack_token:
