---
# kubectl expose pod -n colossal --type=ClusterIP --cluster-ip=None jupyter-driver --port=2222 --target-port=2222
apiVersion: v1
kind: Service
metadata:
  name: jupyter-driver
spec:
  type: ClusterIP
  clusterIP: "None"
  selector:
    app: jupyterhub
    hub.jupyter.org/username: jovyan
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
