###################################################### spark ######################################################
spark:
  image:
    registry: docker.io
    repository: bitnami/spark
    tag: 3.5.0
  enabled: true
  worker:
    #memoryLimit: 1024
    autoscaling:
      minReplicas: 1
      maxReplicas: 2

###################################################### jupyterhub ######################################################
jupyterhub:
  enabled: true
  hub:
    service:
      type: ClusterIP
  singleuser:
    image:
      name: jupyter/pyspark-notebook
      tag: x86_64-spark-3.5.0
    networkPolicy:
      enabled: false


###################################################### Minio ######################################################
minio:
  enabled: true
  mode: standalone
  existingSecret: minio-root-secret
  replicas: 1
  # https://github.com/minio/console/issues/2539#issuecomment-1619211962
  environment:
    MINIO_BROWSER_LOGIN_ANIMATION: "off"
  metrics:
    serviceMonitor:
      enabled: true
  persistence:
    size: 20Gi
  users:
    - accessKey: analyst
      policy: readwrite
      secretKey: analyst123
      # Use a secure password
      #existingSecret: analyst-s3-access-key
      #existingSecretKey: password
  svcaccts:
    - accessKey: analyst-svcacct
      secretKey: analyst123
      # Use a secure password
      #existingSecret: analyst-s3-access-key
      #existingSecretKey: secretKey
      user: analyst
  buckets:
    - name: "logs-bronze"
    - name: "logs-silver"
    - name: "logs-gold"
    - name: "fallback"
