version: '3.3'
services:
  osquery-client:
    image: osquery-client
    networks:
      - kolide_kolide-backend
    configs:
      - source: nginx-cert
        target: /etc/osquery/certificate.crt
      - source: osquery-conf
        target: /etc/osquery/osquery.conf
      - source: osquery-flags
        target: /etc/osquery/osquery.flags

configs:
  nginx-cert:
    file: ./conf/nginx/certs/kolide.crt
  osquery-conf:
    file: ./conf/osquery/osquery.conf
  osquery-flags:
    file: ./conf/osquery/osquery.flags

networks:
  kolide_kolide-backend:
    external: true
