version: '2.2'
services:
  osquery-client:
    build:
      context: .
      dockerfile: Dockerfile-osquery
    networks: 
      - kolide-docker_kolide-backend
    volumes:
      - ./conf/nginx/certs/kolide.crt:/etc/osquery/certificate.crt
      - ./conf/osquery/osquery.conf:/etc/osquery/osquery.conf
      - ./conf/osquery/osquery.flags:/etc/osquery/osquery.flags
    
networks: 
  kolide-docker_kolide-backend:
    external: true
  