FROM ubuntu:18.04

# Install things
RUN apt-get update -y && apt-get install wget unzip mysql-client curl -y

# Create kolide user
RUN useradd -ms /bin/bash kolide

# Donwload Kolide
RUN cd /tmp && \
    wget https://dl.kolide.co/bin/fleet_latest.zip && \
    unzip fleet_latest.zip 'linux/*' -d fleet && \
    cp fleet/linux/fleet /usr/bin/fleet && \
    cp fleet/linux/fleetctl /usr/bin/fleetctl

# Create Kolide dir
RUN mkdir /etc/kolide
RUN mkdir /var/log/kolide
RUN chown kolide:kolide /var/log/kolide

# Setup entrypoint
COPY conf/kolide/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Change user
USER kolide

# Run Kolide
ENTRYPOINT [ "/entrypoint.sh" ]
