FROM ubuntu:18.04

# Build arg
ARG osquery_enroll_secret=changeme

# Install things
RUN apt-get update -y && apt-get install gnupg software-properties-common -y

RUN export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $OSQUERY_KEY && \
    add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main' && \
    apt-get update -y && \
    apt-get install osquery -y

RUN echo $osquery_enroll_secret > /etc/osquery/enroll_secret
RUN echo ${osquery_enroll_secret}


CMD ["osqueryd","--flagfile","/etc/osquery/osquery.flags"]
