version: "2.0"
services:
  cowrie:
    restart: always
    image: wonderfall/cowrie
    links:                           ### MySQL output
      - cowrie-db:cowrie-db          ### MySQL output
    ports:
      - "2222:2222"
    volumes:
      - /srv/cowrie/dl:/cowrie/dl
      - /srv/cowrie/log:/cowrie/log
      - /srv/cowrie/custom:/custom
  cowrie-db:
    restart: always
    image: mariadb:10
    volumes:
      - /srv/cowrie/db:/var/lib/mysql
      - /srv/cowrie/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=cowrie
      - MYSQL_USER=cowrie
      - MYSQL_PASSWORD=supersecretpassword
