ARG NGINX_VERSION
FROM nginx:${NGINX_VERSION}

# Copy SSL
RUN mkdir /etc/nginx/ssl
COPY conf/ssl/docker.key /etc/nginx/ssl/nginx.key
COPY conf/ssl/docker.crt /etc/nginx/ssl/nginx.crt
COPY conf/ssl/dhparam.pem /etc/nginx/ssl/dhparam.pem

# Copy configs
COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx/kibana.conf /etc/nginx/conf.d/kibana.conf
