FROM docker.elastic.co/logstash/logstash:7.0.0

# Install RELP plugin
RUN /usr/share/logstash/bin/logstash-plugin install logstash-input-relp

# Copy certs
RUN mkdir /usr/share/logstash/ssl
COPY Docker/logstash/certs/logstash.crt /usr/share/logstash/ssl/logstash.crt
COPY Docker/logstash/certs/logstash.key /usr/share/logstash/ssl/logstash.key

# Copy pipeline configs
COPY Docker/logstash/pipeline/ /usr/share/logstash/pipeline
RUN rm -rf /usr/share/logstash/pipeline/logstash.conf