ARG LOGSTASH_VERSION
FROM logstash:${LOGSTASH_VERSION}

# Copy certs
COPY conf/ssl/docker.crt /usr/share/logstash/ssl/logstash.crt
COPY conf/ssl/docker.key /usr/share/logstash/ssl/logstash.key

# Copy logstash.yml
RUN rm -rf /usr/share/logstash/pipeline/logstash.conf
COPY conf/logstash/logstash.yml /usr/share/logstash/config/logstash.yml

# Copy pipeline configs
COPY conf/logstash/pipeline/ /usr/share/logstash/pipeline
