####################################################################
# Install/Setup OSQuery
####################################################################
- name: Add OSQuery repo key for Ubuntu
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B

- name: Add OSquery repo for Ubuntu
  apt_repository:
    repo: deb [arch=amd64] https://pkg.osquery.io/deb deb main
    state: present

- name: Install OSQuery
  package:
    name: osquery
    state: present

- name: Copy OSQuery rules conf
  template:
    src: 'conf/osquery/osquery.conf'
    dest: '/etc/osquery/osquery.conf'
    owner: root
    group: root
    mode: '0400'

- name: Enable OSQuery service
  service:
    name: osqueryd
    state: restarted
    enabled: true
