version: "2.2"
services:
  splunk:
    image: splunk/splunk:8.0.7-debian
    container_name: 'splunk'
    restart: unless-stopped
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Changeme123!
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
      - 9997:9997
    networks:
      - default
    volumes:
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
      - ./hello_world:/opt/splunk/etc/apps/hello_world
      - ./hybrid_analysis_cred_store_search_command:/opt/splunk/etc/apps/hybrid_analysis_cred_store_search_command
      - ./community_id_pip_search_command:/opt/splunk/etc/apps/community_id_pip_search_command
    cpus: 2
    mem_limit: 1G

volumes:
  splunk-var:
  splunk-etc:
