version: '3.4'
services:
  splunk:
    image: splunk/splunk:7.2
    restart: unless-stopped
    ports:
      - 9997:9997
      - 5000:5000
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    volumes:
      - splunk-etc:/opt/splunk/etc
      - splunk-var:/opt/splunk/var
    networks:
      - backend
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - splunk
    volumes:
      - ./conf/nginx/cert:/etc/nginx/certs
      - ./conf/nginx/nginx_splunk.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
      - backend

volumes:
  splunk-etc:
  splunk-var:

networks:
  backend:
