
- hosts: 'rsyslog-client'
  become: yes
  become_user: root
  tasks:
    - include_vars: 'group_vars/logging.yml'
    - import_tasks: 'roles/osquery/setup_osquery.yml'
    - import_tasks: 'roles/rsyslog_client/setup_rsyslog.yml'
