FROM nginx:latest

# Copy certs
RUN mkdir /etc/nginx/ssl
COPY conf/nginx/ssl/nginx.crt /etc/nginx/ssl/nginx.crt
COPY conf/nginx/ssl/nginx.key /etc/nginx/ssl/nginx.key

# Copy configs
COPY conf/nginx/nginx_splunk.conf /etc/nginx/conf.d/default.conf
#COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
