FROM ubuntu:18.04

# Install things
RUN apt update -y && apt install python3 python3-pip -y

# Copy app
COPY app /app
WORKDIR /app

# Install python packages
RUN pip3 install -r requirements.txt


CMD ["python3","-u","run_server.py"]
