FROM ubuntu:18.04

# Update
RUN apt-get update -y

### Add Rsyslog repo ###
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:adiscon/v8-stable
RUN apt-get update -y

#### Install/Setup Ryslog ####
RUN apt-get install rsyslog rsyslog-kafka rsyslog-mmjsonparse -y

# Copy configs
COPY conf/rsyslog-server/rsyslog.conf /etc/rsyslog.conf
COPY conf/rsyslog-server/01-osquery-input.conf /etc/rsyslog.d/01-osquery-input.conf
COPY conf/rsyslog-server/02-osquery-to-kafka.conf /etc/rsyslog.d/02-osquery-to-kafka.conf
COPY conf/rsyslog-server/03-output-splunk.conf /etc/rsyslog.d/03-output-splunk.conf

# Expose port
EXPOSE 1514/udp

# Run rsyslog
CMD ["/usr/sbin/rsyslogd", "-n", "-f", "/etc/rsyslog.conf"]
