version: "2.2"
services:
  ############################################ Boundary controller ############################################
  boundary-controller:
    container_name: 'boundary-controller'
    restart: unless-stopped
    command: "server -config /boundary/controller.hcl"
    build:
      context: .
      dockerfile: docker/Dockerfile-boundary-controller
      args:
        - BOUNDARY_VERSION=${BOUNDARY_VERSION}
        - BASE_DOMAIN=hackinglab.local
        - VAULT_ADDR=https://vault.hackinglab.local:443
    environment:
      - VAULT_KMS_ROOT_TOKEN=s.UvrhSDojoB8FZWVhaM85ur9m
      - VAULT_KMS_WORKER_TOKEN=s.P13b1wfHO6aUMrCFVjt1KkjI
      - VAULT_KMS_RECOVERY_TOKEN=s.lzTP7KKDTYJZy2clja1Zkff8
    networks:
      - default
      - boundary-backend
    ports:
      - 9200:9200
    cpus: 1
    mem_limit: 300M

  ############################################ Boundary worker01 ############################################
  boundary-worker01:
    container_name: 'boundary-worker01'
    restart: unless-stopped
    environment:
      - VAULT_KMS_WORKER_TOKEN="s.P13b1wfHO6aUMrCFVjt1KkjI"
    build:
      context: .
      dockerfile: docker/Dockerfile-boundary-worker
      args:
        - BOUNDARY_VERSION=${BOUNDARY_VERSION}
        - BASE_DOMAIN='hackinglab.local'
        - VAULT_ADDR='https://vault.hackinglab.local:443'
    networks:
      - boundary-backend
    cpus: 1
    mem_limit: 300M

  # ############################################ Boudnary worker 02 ############################################
  # boundary-worker02:
  #   container_name: 'boundary-worker02'
  #   restart: unless-stopped
  #   build_args:
  #     - VAULT_KMS_WORKER_TOKEN: ${VAULT_KMS_WORKER_TOKEN}
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-boundary-worker
  #   networks:
  #     - boundary-backend
  #   cpus: 1
  #   mem_limit: 300M

  # ############################################ Boundary worker 03 ############################################
  # boundary-worker03:
  #   container_name: 'boundary-worker03'
  #   restart: unless-stopped
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-boundary-worker
  #   networks:
  #     - boundary-backend
  #   cpus: 1
  #   mem_limit: 300M

networks:
  boundary-backend:
