FROM nginx:1.18.0-alpine

# Copy SSL
RUN mkdir /etc/nginx/ssl
COPY conf/tls/signed_cert/*.crt /etc/nginx/ssl/nginx.crt
COPY conf/tls/signed_cert/*.pem /etc/nginx/ssl/nginx.pem
#COPY conf/tls/mutual_tls/*.crt /etc/nginx/ssl/client_cert.pem
COPY conf/tls/root_ca/CA_cert.crt /etc/nginx/ssl/client_cert.pem

# Copy configs
COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx/mutual-tls.conf /etc/nginx/conf.d/mutual-tls.conf
