FROM nginx:1.18.0-alpine

# Copy SSL
RUN mkdir /etc/nginx/ssl
COPY conf/tls/signed_cert/*.crt /etc/nginx/ssl/nginx.crt
COPY conf/tls/signed_cert/*.pem /etc/nginx/ssl/nginx.pem

# Copy configs
COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx/signed-cert.conf /etc/nginx/conf.d/signed-cert.conf
