FROM ubuntu:18.04 as zeek-build

ENV DEBIAN_FRONTEND noninteractive

# install prereqs
RUN apt-get update -y && apt-get install cmake make gcc g++ flex bison libpcap-dev libssl-dev python-dev swig zlib1g-dev git -y

# Download Zeek
RUN cd /tmp && git clone --recursive https://github.com/zeek/zeek

# Compile Zeek
RUN cd /tmp/zeek && \
    ./configure --prefix=/opt/bro/ && \
    make && \
    make install

# Delete Zeek download
RUN rm -rf /tmp/zeek
