####################################################################
#  Setup Firewall
####################################################################
- name: Setup Ubuntu UFW firewall
  ufw:
    rule: allow
    name: OpenSSH
- ufw:
    rule: allow
    name: Nginx HTTP
- ufw:
    rule: allow
    name: Nginx HTTPS
- ufw:
    state: enabled
    policy: deny
