version: '2.2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: kafka-encricher-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-backend
    cpus: 1
    mem_limit: 150M

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-encricher-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka.local:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - default
      - kafka-backend
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    cpus: 2
    mem_limit: 1G


networks:
  kafka-backend:
