version: '2.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-encricher-app
    restart: unless-stopped
    volumes:
      - ./config/config.py:/app/config/config.py:ro
    cpus: 1
    mem_limit: 20MB
