FROM ubuntu:18.04

# Update
RUN apt-get update -y

#### Add Rsyslog repo ####
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:adiscon/v8-stable
RUN apt-get update -y

#### Install/Setup Ryslog ####
RUN apt-get install rsyslog rsyslog-kafka rsyslog-mmjsonparse rsyslog-relp -y

#### Copy configs ####
# Main rsyslog config
COPY conf/rsyslog/rsyslog-server/rsyslog.conf /etc/rsyslog.conf

# Input config
COPY conf/rsyslog/rsyslog-server/01-input.conf /etc/rsyslog.d/01-input.conf

# Zeek configs
COPY conf/rsyslog/rsyslog-server/11-zeek-to-kafka.conf /etc/rsyslog.d/11-zeek-to-kafka.conf
COPY conf/rsyslog/rsyslog-server/30-osquery-to-splunk.conf /etc/rsyslog.d/30-osquery-to-splunk.conf

# Osquery configs
COPY conf/rsyslog/rsyslog-server/10-osquery-to-kafka.conf /etc/rsyslog.d/10-osquery-to-kafka.conf
COPY conf/rsyslog/rsyslog-server/31-zeek-to-splunk.conf /etc/rsyslog.d/31-zeek-to-splunk.conf

# Expose port
EXPOSE 1514/udp

# Run rsyslog
CMD ["/usr/sbin/rsyslogd", "-n", "-f", "/etc/rsyslog.conf"]
