FROM nginx:latest

RUN mkdir /etc/nginx/ssl
COPY conf/nginx/ssl/splunk.crt /etc/nginx/ssl/splunk.crt
COPY conf/nginx/ssl/splunk.key /etc/nginx/ssl/splunk.key

COPY conf/nginx/default.conf /etc/nginx/conf.d/default.conf
