########################################################
# Run malicious commands
########################################################
- name: Run malicious commands
  ansible.builtin.shell: '{{ item }}'
  async: 45
  poll: 0
  with_lines:
    - cat "cmds/malicious_commands" | grep -v "#"
