version: "3.9"
services:
  squid:
    image: squid-tls-termination:latest
    configs:
      - source: squid-config
        target: /etc/squid/squid.conf
    secrets:
      - source: squid-tls-cert
        target: /etc/ssl/crt/squid.crt
      - source: squid-tls-key
        target: /etc/ssl/key/squid.key
      - source: squid-tls-ca
        target: /etc/ssl/CA/cacert.crt
      - source: squid-client-int-ca
        target: /etc/ssl/CA/client-ca.crt
    #networks:
    #  #- default
    ports:
      - 3128:3128
      - 3129:3129
    volumes:
      - squid-cahce:/var/cache/squid
      - squid-logs:/var/log/squid
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s

configs:
  squid-config:
    file: conf/squid/squid.conf

secrets:
  squid-tls-cert:
    external: true
    #file: ./conf/tls/squid01_proxy.crt
    #file: ./conf/tls/squid.crt
  squid-tls-key:
    external: true
    #file: ./conf/tls/squid01_proxy.key
    #file: ./conf/tls/squid.key
  squid-tls-ca:
    #external: true
    file: ./root_ca.crt
    #  file: ./conf/tls/proxy_int.crt
  squid-client-int-ca:
    external: true


volumes:
  squid-cahce:
  squid-logs:
