####################################################################
#  Install/Setup MySQL
####################################################################
- name: Add OSQuery repo key for CentOS
  rpm_key:
    state: present
    key: https://pkg.osquery.io/rpm/GPG

- name: Add OSQuery repo for CentOS
  yum_repository:
    name: osquery-s3-rpm-repo
    enabled: true
    description: OSQuery repo
    baseurl: https://pkg.osquery.io/rpm/$basearch/
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-osquery
    gpgcheck: true

- name: Install OSQuery
  package:
    name: osquery
    state: installed

- name: Get cert for Kolide
  shell: python -c "import ssl; print ssl.get_server_certificate(('{{ fleet_hostname }}.{{ base_domain }}', 443))" | sudo tee /etc/osquery/certificate.crt

- name: Copy OSQuery flags file
  template:
    src: conf/agents/osquery.flags
    dest: /etc/osquery/osquery.flags
    owner: root
    group: root
    mode: '0600'

- name: Copy OSQuery secret
  template:
    src: conf/agents/osquery.key
    dest: /etc/osquery/osquery.key
    owner: root
    group: root
    mode: '0600'

- name: Enable OSQuery service
  service:
    name: osqueryd
    state: restarted
    enabled: true
