version: '2.2'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: unless-stopped
    networks:
      - kafka-backend
    depends_on:
      - kafka
    cpu_count: 1
    mem_limit: 100M
  rsyslog:
    build: .
    restart: unless-stopped
    networks:
      - default
      - kafka-backend
    ports:
      - 1514:1514/udp
    depends_on:
      - kafka
    cpu_count: 1
    mem_limit: 150M
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    networks:
      - kafka-backend
    cpu_count: 1
    mem_limit: 150M
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'kafka-test.hackinglab.local'
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-backend
    depends_on:
      - zookeeper
    cpu_count: 2
    mem_limit: 500M

networks:
  kafka-backend:
    driver: overlay
