version: '2.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - kafka-backend
    cpu_count: 1
    mem_limit: 150M
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - "9098:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'kafka-test.hackinglab.local'
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - default
      - kafka-backend
    cpu_count: 2
    mem_limit: 500M
  
    
networks:
  kafka-backend:
    driver: overlay