version: '2.2'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: unless-stopped
    networks:
      - osquery_kafka_rsyslog_kafka-backend
    cpu_count: 1
    mem_limit: 100M

networks:
  osquery_kafka_rsyslog_kafka-backend:
    driver: overlay
    external: true
