version: "2.2"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx-mutual-tls
    restart: unless-stopped
    networks:
      - default
      - whoami-backend
    ports:
      - 8000:80
      - 8443:443
  whoami:
    image: containous/whoami:v1.5.0
    restart: unless-stopped
    networks:
      - whoami-backend

networks:
  whoami-backend:
