version: "2.2"
services:
  ################################################## Vault ##################################################
  vault:
    build:
      context: .
      dockerfile: docker/Dockerfile-vault
    container_name: 'vault-app'
    restart: unless-stopped
    networks:
      - default
      - vault-backend
    ports:
      - 8200:8200
    volumes:
      - vault-config:/vault/config
      - vault-policies:/vault/policies
      - vault-data:/vault/data
      - vault-logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul

  ################################################## Consul ##################################################
  consul:
    build:
      context: .
      dockerfile: docker/Dockerfile-consul
    container_name: 'vault-consul'
    restart: unless-stopped
    networks:
      #- default
      - vault-backend
    volumes:
      - consul-data:/consul/data

volumes:
  consul-config:
  consul-data:
  vault-config:
  vault-policies:
  vault-data:
  vault-logs:

networks:
  vault-backend:
